#test_11_visibilityarea_unknown_smallfov.yaml
experiment:
  name: CMP_01_unknown_smallfov__visibility_area
  dt: 0.05
  exploration_algorithm: CoScan
  show_animation: false
  save_animation: false
  max_ticks: 5000

environment:
  width: 20.0
  height: 20.0
  resolution: 0.1
  circles: []
  superellipsoids: []
  unknown_obstacles:
    - [6.0, 6.0, 0.6]
    - [9.0, 9.0, 0.6]

robots:
  common:
    model: DoubleIntegrator2D
    sensor: rgbd
    exploration: true
    reached_threshold: 2.0
    radius: 0.25
    cam_range: 4.0
    fov_angle: 40.0
  instances:
    - robot_id: 0
      x0: [2.0, 2.0, 0.0, 0.0, 0.0]
    - robot_id: 1
      x0: [2.0, 10.0, 0.0, 0.0, 0.0]

controller:
  pos: mpc_cbf
  att: visibility_area
