experiment:
  name: EXP_00_empty_map
  dt: 0.05
  exploration_algorithm: CoScan
  show_animation: false
  save_animation: false
  max_ticks: 5000

environment:
  width: 20.0
  height: 18.0
  resolution: 0.1
  circles: []
  superellipsoids: []
  unknown_obstacles: []

robots:
  common:
    model: DoubleIntegrator2D
    sensor: rgbd
    exploration: true
    reached_threshold: 2.0
    radius: 0.25
    cam_range: 5.0
    fov_angle: 80.0
  instances:
    - robot_id: 0
      x0: [2.0, 2.0, 0.0, 0.0, 0.0]
    - robot_id: 1
      x0: [2.0, 10.0, 0.0, 0.0, 0.0]

controller:
  pos: mpc_cbf
  att: gatekeeper
